name: Deploy

on:
  push:
    tags:
        - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: '7.4'
        extensions: ssh2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Detecting PHP Code Standards Violations
      run: composer check

    - name: Create zip
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        TAG_NUMBER=$(echo $TAG_NAME | sed 's/[^0-9v.]*//g')
        git archive -o application-ci.tar.gz $TAG_NUMBER
      working-directory: ${{ github.workspace }}

    - name: Copy via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "application-ci.tar.gz"
        target: /home/u508598207/app/pre-deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/u508598207/app/ci-github-php-hostinger/
            tar -xzf /home/u508598207/app/pre-deploy/application-ci.tar.gz -C /home/u508598207/app/ci-github-php-hostinger/
            cd /home/u508598207/app/ci-github-php-hostinger/
            composer install --prefer-dist --no-progress --no-suggest
